### ISSUE TITLE
fastddsgen -python Can't find template definition_list.st

### ISSUE THREAD

**Issue by michaelchao** [eProsima/Fast-DDS-Gen#181]
I Clone newest code. After compiled and use it, the whole output is
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
Loading templates...
Processing the file simple.image.idl...
ERROR<Exception>: Can't find template definition_list.st; group hierarchy is [FastCdrCommon]
Exception in thread "main" java.lang.NullPointerException
        at com.eprosima.fastdds.fastddsgen.execute(fastddsgen.java:407)
        at com.eprosima.fastdds.fastddsgen.main(fastddsgen.java:1481)
```

**Comment by michaelchao** [comment]
**swig** binary must be installed and can be found by **fastddsgen** before you run **fastddsgen**
