### ISSUE TITLE
fastddsgen.jar internal exception while generating code from idl

### ISSUE THREAD

**Issue by ghostravenstorm** [eProsima/Fast-DDS-Gen#47]
Running the jar file to build code from an idl file halts at an exception.

```
Loading templates...
Processing the file H:/Storage/Vcom3D/AMM/Projects/_CompatibilityTestingWorkspace/FastDdsCpp01/Nike.idl...
ERROR<callPreprocessor>: Cannot execute the preprocessor. Reason: Cannot run program "cl.exe": CreateProcess error=2, The system cannot find the file specified
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.eprosima.fastdds.solution.Project.getIDLIncludeFiles()" because "project" is null
        at com.eprosima.fastdds.fastddsgen.execute(fastddsgen.java:343)
        at com.eprosima.fastdds.fastddsgen.main(fastddsgen.java:1207)
```

This is from running the fastddsgen bat script.

Not sure if I built the tool corrrrectly. I working with a lack of instructions.
I cloned the repo, ran `gradle build` then just ran the scripts until I hit this error.

**Comment by ghostravenstorm** [comment]
Turns out this needs to run from a VS command prompt.
