### ISSUE TITLE
issue with running fastddsgen with HelloWorld.idl [13896]

### ISSUE THREAD

**Issue by WillTNSW** [eProsima/Fast-DDS-Gen#93]
I am running this under windows with eProsima Fast DDS 2.5.0 installed and SWIG 4.0.2

Running the command 
```
fastddsgen -python HelloWorld.idl
```
in the HelloWorldExample directory yield a exception.
```
PS C:\repos\FastDDSPython\Fast-DDS-python\fastdds_python_examples> cd .\HelloWorldExample\
PS C:\repos\FastDDSPython\Fast-DDS-python\fastdds_python_examples\HelloWorldExample> fastddsgen -python HelloWorld.idl
Loading templates...
Processing the file HelloWorld.idl...
ERROR<callPreprocessor>: Cannot execute the preprocessor. Reason: Cannot run program "cl.exe": CreateProcess error=2, The system cannot find the file specified
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.eprosima.fastdds.solution.Project.getIDLIncludeFiles()" because "project" is null
        at com.eprosima.fastdds.fastddsgen.execute(fastddsgen.java:401)
        at com.eprosima.fastdds.fastddsgen.main(fastddsgen.java:1474)
PS C:\repos\FastDDSPython\Fast-DDS-python\fastdds_python_examples\HelloWorldExample> 
```

am I missing some include files as suggested in error?

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to proceed and close this due to inactivity. @WillTNSW, please feel free to reopen in case that the issue is still happening.
